//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Balanca.servicoBalanca {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CadBalancaRegistraPesoDTOBalanca", Namespace="http://www.gl2sistemas.com/")]
    [System.SerializableAttribute()]
    public partial class CadBalancaRegistraPesoDTOBalanca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErroField;
        
        private int IdPorJanelaField;
        
        private int IdUnidadeOperacionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaVeiculoField;
        
        private System.Nullable<decimal> PesoBalancaEntradaField;
        
        private System.Nullable<decimal> PesoBalancaSaidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Erro {
            get {
                return this.ErroField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroField, value) != true)) {
                    this.ErroField = value;
                    this.RaisePropertyChanged("Erro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdPorJanela {
            get {
                return this.IdPorJanelaField;
            }
            set {
                if ((this.IdPorJanelaField.Equals(value) != true)) {
                    this.IdPorJanelaField = value;
                    this.RaisePropertyChanged("IdPorJanela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int IdUnidadeOperacional {
            get {
                return this.IdUnidadeOperacionalField;
            }
            set {
                if ((this.IdUnidadeOperacionalField.Equals(value) != true)) {
                    this.IdUnidadeOperacionalField = value;
                    this.RaisePropertyChanged("IdUnidadeOperacional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PlacaVeiculo {
            get {
                return this.PlacaVeiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaVeiculoField, value) != true)) {
                    this.PlacaVeiculoField = value;
                    this.RaisePropertyChanged("PlacaVeiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> PesoBalancaEntrada {
            get {
                return this.PesoBalancaEntradaField;
            }
            set {
                if ((this.PesoBalancaEntradaField.Equals(value) != true)) {
                    this.PesoBalancaEntradaField = value;
                    this.RaisePropertyChanged("PesoBalancaEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> PesoBalancaSaida {
            get {
                return this.PesoBalancaSaidaField;
            }
            set {
                if ((this.PesoBalancaSaidaField.Equals(value) != true)) {
                    this.PesoBalancaSaidaField = value;
                    this.RaisePropertyChanged("PesoBalancaSaida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CadBalancaDTOBalanca", Namespace="http://www.gl2sistemas.com/")]
    [System.SerializableAttribute()]
    public partial class CadBalancaDTOBalanca : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErroField;
        
        private int IdPorJanelaField;
        
        private int IdUnidadeOperacionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaVeiculoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MotoristaField;
        
        private System.Nullable<decimal> PesoEntradaField;
        
        private System.Nullable<decimal> PesoSaidaField;
        
        private System.Nullable<decimal> PesoAcondicionadoField;
        
        private System.Nullable<decimal> PesoLiquidoField;
        
        private System.Nullable<System.DateTime> DataEntradaPrevistaField;
        
        private System.Nullable<System.DateTime> DataEntradaRealField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Erro {
            get {
                return this.ErroField;
            }
            set {
                if ((object.ReferenceEquals(this.ErroField, value) != true)) {
                    this.ErroField = value;
                    this.RaisePropertyChanged("Erro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int IdPorJanela {
            get {
                return this.IdPorJanelaField;
            }
            set {
                if ((this.IdPorJanelaField.Equals(value) != true)) {
                    this.IdPorJanelaField = value;
                    this.RaisePropertyChanged("IdPorJanela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int IdUnidadeOperacional {
            get {
                return this.IdUnidadeOperacionalField;
            }
            set {
                if ((this.IdUnidadeOperacionalField.Equals(value) != true)) {
                    this.IdUnidadeOperacionalField = value;
                    this.RaisePropertyChanged("IdUnidadeOperacional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PlacaVeiculo {
            get {
                return this.PlacaVeiculoField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaVeiculoField, value) != true)) {
                    this.PlacaVeiculoField = value;
                    this.RaisePropertyChanged("PlacaVeiculo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Motorista {
            get {
                return this.MotoristaField;
            }
            set {
                if ((object.ReferenceEquals(this.MotoristaField, value) != true)) {
                    this.MotoristaField = value;
                    this.RaisePropertyChanged("Motorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> PesoEntrada {
            get {
                return this.PesoEntradaField;
            }
            set {
                if ((this.PesoEntradaField.Equals(value) != true)) {
                    this.PesoEntradaField = value;
                    this.RaisePropertyChanged("PesoEntrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> PesoSaida {
            get {
                return this.PesoSaidaField;
            }
            set {
                if ((this.PesoSaidaField.Equals(value) != true)) {
                    this.PesoSaidaField = value;
                    this.RaisePropertyChanged("PesoSaida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<decimal> PesoAcondicionado {
            get {
                return this.PesoAcondicionadoField;
            }
            set {
                if ((this.PesoAcondicionadoField.Equals(value) != true)) {
                    this.PesoAcondicionadoField = value;
                    this.RaisePropertyChanged("PesoAcondicionado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<decimal> PesoLiquido {
            get {
                return this.PesoLiquidoField;
            }
            set {
                if ((this.PesoLiquidoField.Equals(value) != true)) {
                    this.PesoLiquidoField = value;
                    this.RaisePropertyChanged("PesoLiquido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<System.DateTime> DataEntradaPrevista {
            get {
                return this.DataEntradaPrevistaField;
            }
            set {
                if ((this.DataEntradaPrevistaField.Equals(value) != true)) {
                    this.DataEntradaPrevistaField = value;
                    this.RaisePropertyChanged("DataEntradaPrevista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<System.DateTime> DataEntradaReal {
            get {
                return this.DataEntradaRealField;
            }
            set {
                if ((this.DataEntradaRealField.Equals(value) != true)) {
                    this.DataEntradaRealField = value;
                    this.RaisePropertyChanged("DataEntradaReal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gl2sistemas.com/", ConfigurationName="servicoBalanca.wsBalancaSoap")]
    public interface wsBalancaSoap {
        
        // CODEGEN: Generating message contract since element name dadosBalanca from namespace http://www.gl2sistemas.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gl2sistemas.com/SalvarPesoBalancaJanela", ReplyAction="*")]
        Balanca.servicoBalanca.SalvarPesoBalancaJanelaResponse SalvarPesoBalancaJanela(Balanca.servicoBalanca.SalvarPesoBalancaJanelaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gl2sistemas.com/SalvarPesoBalancaJanela", ReplyAction="*")]
        System.Threading.Tasks.Task<Balanca.servicoBalanca.SalvarPesoBalancaJanelaResponse> SalvarPesoBalancaJanelaAsync(Balanca.servicoBalanca.SalvarPesoBalancaJanelaRequest request);
        
        // CODEGEN: Generating message contract since element name placaVeiculo from namespace http://www.gl2sistemas.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gl2sistemas.com/ListaBalancasCadastradas", ReplyAction="*")]
        Balanca.servicoBalanca.ListaBalancasCadastradasResponse ListaBalancasCadastradas(Balanca.servicoBalanca.ListaBalancasCadastradasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gl2sistemas.com/ListaBalancasCadastradas", ReplyAction="*")]
        System.Threading.Tasks.Task<Balanca.servicoBalanca.ListaBalancasCadastradasResponse> ListaBalancasCadastradasAsync(Balanca.servicoBalanca.ListaBalancasCadastradasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalvarPesoBalancaJanelaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalvarPesoBalancaJanela", Namespace="http://www.gl2sistemas.com/", Order=0)]
        public Balanca.servicoBalanca.SalvarPesoBalancaJanelaRequestBody Body;
        
        public SalvarPesoBalancaJanelaRequest() {
        }
        
        public SalvarPesoBalancaJanelaRequest(Balanca.servicoBalanca.SalvarPesoBalancaJanelaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gl2sistemas.com/")]
    public partial class SalvarPesoBalancaJanelaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Balanca.servicoBalanca.CadBalancaRegistraPesoDTOBalanca dadosBalanca;
        
        public SalvarPesoBalancaJanelaRequestBody() {
        }
        
        public SalvarPesoBalancaJanelaRequestBody(Balanca.servicoBalanca.CadBalancaRegistraPesoDTOBalanca dadosBalanca) {
            this.dadosBalanca = dadosBalanca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SalvarPesoBalancaJanelaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SalvarPesoBalancaJanelaResponse", Namespace="http://www.gl2sistemas.com/", Order=0)]
        public Balanca.servicoBalanca.SalvarPesoBalancaJanelaResponseBody Body;
        
        public SalvarPesoBalancaJanelaResponse() {
        }
        
        public SalvarPesoBalancaJanelaResponse(Balanca.servicoBalanca.SalvarPesoBalancaJanelaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gl2sistemas.com/")]
    public partial class SalvarPesoBalancaJanelaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Balanca.servicoBalanca.CadBalancaRegistraPesoDTOBalanca SalvarPesoBalancaJanelaResult;
        
        public SalvarPesoBalancaJanelaResponseBody() {
        }
        
        public SalvarPesoBalancaJanelaResponseBody(Balanca.servicoBalanca.CadBalancaRegistraPesoDTOBalanca SalvarPesoBalancaJanelaResult) {
            this.SalvarPesoBalancaJanelaResult = SalvarPesoBalancaJanelaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaBalancasCadastradasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaBalancasCadastradas", Namespace="http://www.gl2sistemas.com/", Order=0)]
        public Balanca.servicoBalanca.ListaBalancasCadastradasRequestBody Body;
        
        public ListaBalancasCadastradasRequest() {
        }
        
        public ListaBalancasCadastradasRequest(Balanca.servicoBalanca.ListaBalancasCadastradasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gl2sistemas.com/")]
    public partial class ListaBalancasCadastradasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<System.DateTime> dataEntradaPrevista;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string placaVeiculo;
        
        public ListaBalancasCadastradasRequestBody() {
        }
        
        public ListaBalancasCadastradasRequestBody(System.Nullable<System.DateTime> dataEntradaPrevista, string placaVeiculo) {
            this.dataEntradaPrevista = dataEntradaPrevista;
            this.placaVeiculo = placaVeiculo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListaBalancasCadastradasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListaBalancasCadastradasResponse", Namespace="http://www.gl2sistemas.com/", Order=0)]
        public Balanca.servicoBalanca.ListaBalancasCadastradasResponseBody Body;
        
        public ListaBalancasCadastradasResponse() {
        }
        
        public ListaBalancasCadastradasResponse(Balanca.servicoBalanca.ListaBalancasCadastradasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gl2sistemas.com/")]
    public partial class ListaBalancasCadastradasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Balanca.servicoBalanca.CadBalancaDTOBalanca[] ListaBalancasCadastradasResult;
        
        public ListaBalancasCadastradasResponseBody() {
        }
        
        public ListaBalancasCadastradasResponseBody(Balanca.servicoBalanca.CadBalancaDTOBalanca[] ListaBalancasCadastradasResult) {
            this.ListaBalancasCadastradasResult = ListaBalancasCadastradasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsBalancaSoapChannel : Balanca.servicoBalanca.wsBalancaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsBalancaSoapClient : System.ServiceModel.ClientBase<Balanca.servicoBalanca.wsBalancaSoap>, Balanca.servicoBalanca.wsBalancaSoap {
        
        public wsBalancaSoapClient() {
        }
        
        public wsBalancaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsBalancaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsBalancaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsBalancaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balanca.servicoBalanca.SalvarPesoBalancaJanelaResponse Balanca.servicoBalanca.wsBalancaSoap.SalvarPesoBalancaJanela(Balanca.servicoBalanca.SalvarPesoBalancaJanelaRequest request) {
            return base.Channel.SalvarPesoBalancaJanela(request);
        }
        
        public Balanca.servicoBalanca.CadBalancaRegistraPesoDTOBalanca SalvarPesoBalancaJanela(Balanca.servicoBalanca.CadBalancaRegistraPesoDTOBalanca dadosBalanca) {
            Balanca.servicoBalanca.SalvarPesoBalancaJanelaRequest inValue = new Balanca.servicoBalanca.SalvarPesoBalancaJanelaRequest();
            inValue.Body = new Balanca.servicoBalanca.SalvarPesoBalancaJanelaRequestBody();
            inValue.Body.dadosBalanca = dadosBalanca;
            Balanca.servicoBalanca.SalvarPesoBalancaJanelaResponse retVal = ((Balanca.servicoBalanca.wsBalancaSoap)(this)).SalvarPesoBalancaJanela(inValue);
            return retVal.Body.SalvarPesoBalancaJanelaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Balanca.servicoBalanca.SalvarPesoBalancaJanelaResponse> Balanca.servicoBalanca.wsBalancaSoap.SalvarPesoBalancaJanelaAsync(Balanca.servicoBalanca.SalvarPesoBalancaJanelaRequest request) {
            return base.Channel.SalvarPesoBalancaJanelaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Balanca.servicoBalanca.SalvarPesoBalancaJanelaResponse> SalvarPesoBalancaJanelaAsync(Balanca.servicoBalanca.CadBalancaRegistraPesoDTOBalanca dadosBalanca) {
            Balanca.servicoBalanca.SalvarPesoBalancaJanelaRequest inValue = new Balanca.servicoBalanca.SalvarPesoBalancaJanelaRequest();
            inValue.Body = new Balanca.servicoBalanca.SalvarPesoBalancaJanelaRequestBody();
            inValue.Body.dadosBalanca = dadosBalanca;
            return ((Balanca.servicoBalanca.wsBalancaSoap)(this)).SalvarPesoBalancaJanelaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Balanca.servicoBalanca.ListaBalancasCadastradasResponse Balanca.servicoBalanca.wsBalancaSoap.ListaBalancasCadastradas(Balanca.servicoBalanca.ListaBalancasCadastradasRequest request) {
            return base.Channel.ListaBalancasCadastradas(request);
        }
        
        public Balanca.servicoBalanca.CadBalancaDTOBalanca[] ListaBalancasCadastradas(System.Nullable<System.DateTime> dataEntradaPrevista, string placaVeiculo) {
            Balanca.servicoBalanca.ListaBalancasCadastradasRequest inValue = new Balanca.servicoBalanca.ListaBalancasCadastradasRequest();
            inValue.Body = new Balanca.servicoBalanca.ListaBalancasCadastradasRequestBody();
            inValue.Body.dataEntradaPrevista = dataEntradaPrevista;
            inValue.Body.placaVeiculo = placaVeiculo;
            Balanca.servicoBalanca.ListaBalancasCadastradasResponse retVal = ((Balanca.servicoBalanca.wsBalancaSoap)(this)).ListaBalancasCadastradas(inValue);
            return retVal.Body.ListaBalancasCadastradasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Balanca.servicoBalanca.ListaBalancasCadastradasResponse> Balanca.servicoBalanca.wsBalancaSoap.ListaBalancasCadastradasAsync(Balanca.servicoBalanca.ListaBalancasCadastradasRequest request) {
            return base.Channel.ListaBalancasCadastradasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Balanca.servicoBalanca.ListaBalancasCadastradasResponse> ListaBalancasCadastradasAsync(System.Nullable<System.DateTime> dataEntradaPrevista, string placaVeiculo) {
            Balanca.servicoBalanca.ListaBalancasCadastradasRequest inValue = new Balanca.servicoBalanca.ListaBalancasCadastradasRequest();
            inValue.Body = new Balanca.servicoBalanca.ListaBalancasCadastradasRequestBody();
            inValue.Body.dataEntradaPrevista = dataEntradaPrevista;
            inValue.Body.placaVeiculo = placaVeiculo;
            return ((Balanca.servicoBalanca.wsBalancaSoap)(this)).ListaBalancasCadastradasAsync(inValue);
        }
    }
}
